"""add payment_method to subscription

Revision ID: 2714692c9d6a
Revises: add_user_address_fields
Create Date: 2025-03-19 08:52:53.324472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2714692c9d6a'
down_revision = 'add_user_address_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('payment_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'payment_method')
    # ### end Alembic commands ### 