"""add_user_session_fields

Revision ID: 958a5a05fca9
Revises: fb95010fe07a
Create Date: 2025-03-20 20:20:42.367655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '958a5a05fca9'
down_revision = 'fb95010fe07a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adiciona campos para controle de sessão na tabela de usuários
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_activity', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    
    # Adiciona campo para armazenar tokens ativos
    try:
        # Tenta usar JSON nativo se disponível
        op.add_column('users', sa.Column('active_tokens', mysql.JSON(), nullable=True))
    except Exception:
        # Fallback para texto
        op.add_column('users', sa.Column('active_tokens', sa.Text(), nullable=True))
    
    # Atualiza valores padrão
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE users 
        SET failed_login_attempts = 0,
            active_tokens = '[]'
        WHERE active_tokens IS NULL
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove campos adicionados
    op.drop_column('users', 'active_tokens')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_activity')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ### 